import { useState } from 'react'
import { useQuery } from '@tanstack/react-query'
import { ArrowDownLeft, ArrowUpRight, BadgeDollarSign, CircleDollarSign, CreditCard, FileClock, ReceiptText, Search, WalletCards, X } from 'lucide-react'
import { salesClient, type Sale } from './lib/sales-client'
import { Button } from './components/ui/button'

const statusNames: Record<string, string> = { PAID: 'Pago', PENDING: 'Pendente', PROCESSING: 'Processando', EXPIRED: 'Expirado', FAILED: 'Falhou', CANCELLED: 'Cancelado', REFUNDED: 'Reembolsado', CHARGEBACK: 'Chargeback' }
const accountNames: Record<string, string> = { PAYMENT_PROCESSOR_CLEARING: 'Liquidação no processador', MERCHANT_AVAILABLE: 'Saldo disponível', PLATFORM_FEE_REVENUE: 'Taxa Zyven', PROVIDER_FEE_PAYABLE: 'Taxa do provedor' }
function money(value: string, currency = 'BRL') { return new Intl.NumberFormat('pt-BR', { style: 'currency', currency }).format(Number(value)) }
function date(value?: string) { return value ? new Intl.DateTimeFormat('pt-BR', { dateStyle: 'short', timeStyle: 'short' }).format(new Date(value)) : '—' }

function SaleRow({ sale, select }: { sale: Sale; select: () => void }) {
  return <button className="sales-row" onClick={select}><div className="sale-customer"><i>{sale.customerName.slice(0, 2).toLocaleUpperCase('pt-BR')}</i><span><strong>{sale.customerName}</strong><small>{sale.customerEmail}</small></span></div><span>{sale.offerName}</span><span className={`sale-status ${sale.status.toLocaleLowerCase()}`}><i />{statusNames[sale.status] ?? sale.status}</span><span className="sale-value"><strong>{money(sale.grossAmount, sale.currency)}</strong><small>Líquido {money(sale.netAmount, sale.currency)}</small></span><time>{date(sale.paidAt ?? sale.createdAt)}</time></button>
}

export function Sales({ org, userId }: { org: string; userId: string }) {
  const [tab, setTab] = useState<'sales' | 'ledger'>('sales'); const [status, setStatus] = useState(''); const [page, setPage] = useState(1); const [ledgerPage, setLedgerPage] = useState(1); const [selected, setSelected] = useState('')
  const summary = useQuery({ queryKey: ['organizations', userId, org, 'finance', 'summary'], queryFn: () => salesClient.summary(org), retry: false })
  const sales = useQuery({ queryKey: ['organizations', userId, org, 'finance', 'sales', page, status], queryFn: () => salesClient.sales(org, page, status), retry: false })
  const ledger = useQuery({ queryKey: ['organizations', userId, org, 'finance', 'ledger', ledgerPage], queryFn: () => salesClient.ledger(org, ledgerPage), enabled: tab === 'ledger', retry: false })
  const detail = useQuery({ queryKey: ['organizations', userId, org, 'finance', 'sale', selected], queryFn: () => salesClient.detail(org, selected), enabled: Boolean(selected), retry: false })
  const error = summary.error ?? (tab === 'sales' ? sales.error : ledger.error)
  return <section className="sales-page"><header className="sales-heading"><p><BadgeDollarSign />Operação financeira</p><h1>Vendas e financeiro</h1><span>Acompanhe pagamentos, taxas, saldo disponível e lançamentos da organização.</span></header>
    {summary.isPending ? <p role="status">Carregando resumo financeiro...</p> : summary.data && <div className="sales-metrics"><article><i><WalletCards /></i><span>Saldo disponível</span><strong>{money(summary.data.availableBalance, summary.data.currency)}</strong><small>Fonte: ledger imutável</small></article><article><i><CircleDollarSign /></i><span>Total recebido</span><strong>{money(summary.data.totalReceived, summary.data.currency)}</strong><small>{summary.data.paidPayments} pagamentos confirmados</small></article><article><i><ReceiptText /></i><span>Taxas acumuladas</span><strong>{money(summary.data.totalFees, summary.data.currency)}</strong><small>Plataforma e processador</small></article><article><i><CreditCard /></i><span>Pagamentos</span><strong>{summary.data.totalPayments}</strong><small>{summary.data.pendingPayments} pendentes · {summary.data.failedPayments + summary.data.expiredPayments} não concluídos</small></article></div>}
    {error && <div className="error-notice"><p role="alert">Não foi possível carregar os dados financeiros.</p><Button variant="outline" onClick={() => { void summary.refetch(); void (tab === 'sales' ? sales.refetch() : ledger.refetch()) }}>Tentar novamente</Button></div>}
    <nav className="finance-tabs" aria-label="Visões financeiras"><button className={tab === 'sales' ? 'active' : ''} onClick={() => setTab('sales')}><CreditCard />Vendas</button><button className={tab === 'ledger' ? 'active' : ''} onClick={() => setTab('ledger')}><FileClock />Extrato</button></nav>
    {tab === 'sales' && <section className="sales-directory"><div className="sales-toolbar"><div><Search /><span>{sales.data?.total ?? 0} registros</span></div><label>Status<select aria-label="Filtrar vendas por status" value={status} onChange={event => { setStatus(event.target.value); setPage(1) }}><option value="">Todos</option><option value="PAID">Pagos</option><option value="PENDING">Pendentes</option><option value="PROCESSING">Processando</option><option value="EXPIRED">Expirados</option><option value="FAILED">Falhos</option></select></label></div>{sales.isPending ? <p role="status" className="finance-loading">Carregando vendas...</p> : sales.data && !sales.data.total ? <div className="finance-empty"><CreditCard /><h2>Nenhuma venda encontrada</h2><p>Os pagamentos aparecerão aqui quando um comprador gerar uma cobrança.</p></div> : sales.data && <><div className="sales-table-head"><span>Comprador</span><span>Oferta</span><span>Status</span><span>Valores</span><span>Data</span></div>{sales.data.items.map(item => <SaleRow key={item.id} sale={item} select={() => setSelected(item.id)} />)}<Pagination page={page} total={sales.data.total} size={sales.data.pageSize} setPage={setPage} /></>}</section>}
    {tab === 'ledger' && <section className="ledger-list">{ledger.isPending ? <p role="status" className="finance-loading">Carregando extrato...</p> : ledger.data && !ledger.data.total ? <div className="finance-empty"><FileClock /><h2>Extrato vazio</h2><p>Os lançamentos surgirão após a confirmação dos pagamentos.</p></div> : ledger.data && <>{ledger.data.items.map(transaction => <details key={transaction.id}><summary><span><i><ArrowDownLeft /></i><span><strong>Pagamento confirmado</strong><small>{transaction.reference}</small></span></span><span><strong>{date(transaction.occurredAt)}</strong><small>{transaction.entries.length} partidas</small></span></summary><div className="ledger-entries">{transaction.entries.map((entry, index) => <div key={`${entry.accountCode}-${index}`}><span>{accountNames[entry.accountCode] ?? entry.accountCode}<code>{entry.accountCode}</code></span><span className="debit"><ArrowDownLeft />{money(entry.debit, transaction.currency)}</span><span className="credit"><ArrowUpRight />{money(entry.credit, transaction.currency)}</span></div>)}</div></details>)}<Pagination page={ledgerPage} total={ledger.data.total} size={ledger.data.pageSize} setPage={setLedgerPage} /></>}</section>}
    {selected && <aside className="sale-detail" aria-label="Detalhes da venda"><div className="sale-detail-card"><header><div><span>Detalhes da venda</span><h2>{detail.data?.offerName ?? 'Carregando...'}</h2></div><Button variant="ghost" aria-label="Fechar detalhes" onClick={() => setSelected('')}><X /></Button></header>{detail.isPending ? <p role="status">Carregando detalhes...</p> : detail.error ? <p role="alert">Não foi possível carregar esta venda.</p> : detail.data && <><div className="detail-status"><span className={`sale-status ${detail.data.status.toLocaleLowerCase()}`}><i />{statusNames[detail.data.status] ?? detail.data.status}</span><strong>{money(detail.data.grossAmount, detail.data.currency)}</strong></div><dl><div><dt>Comprador</dt><dd>{detail.data.customerName}<small>{detail.data.customerEmail}</small></dd></div><div><dt>Valor líquido</dt><dd>{money(detail.data.netAmount, detail.data.currency)}</dd></div><div><dt>Taxa Zyven</dt><dd>{money(detail.data.platformFee, detail.data.currency)}</dd></div><div><dt>Taxa do provedor</dt><dd>{money(detail.data.providerFee, detail.data.currency)}</dd></div><div><dt>Pagamento</dt><dd>{detail.data.paymentMethod} · {detail.data.provider ?? 'Sem provedor'}</dd></div><div><dt>Pago em</dt><dd>{date(detail.data.paidAt)}</dd></div><div><dt>Direito de acesso</dt><dd>{detail.data.entitlementStatus ?? 'Não gerado'}</dd></div><div><dt>Entrega</dt><dd>{detail.data.fulfillmentStatus ?? 'Não realizada'}</dd></div></dl><code>{detail.data.id}</code></>}</div></aside>}
  </section>
}

function Pagination({ page, total, size, setPage }: { page: number; total: number; size: number; setPage: (value: number) => void }) { if (total <= size) return null; return <div className="pagination"><Button variant="outline" disabled={page <= 1} onClick={() => setPage(page - 1)}>Anterior</Button><span>Página {page} de {Math.ceil(total / size)}</span><Button variant="outline" disabled={page * size >= total} onClick={() => setPage(page + 1)}>Próxima</Button></div> }
